### ISSUE TITLE
All theme colors broken on Rider 2024.2.6

### ISSUE THREAD

**Issue by daramkun** [JetBrains/rider-theme-pack#27] opened 2024-10-10 05:24 UTC
Rider Theme Pack's all theme colors broken on Rider 2024.2.6

keyword highlight color(using, namespace, public, class, true, false, ... without return) and comment color is good but other colors are almost twisted.

**Comment by bukk530** [comment] 2024-10-10 19:37
Same here, all colours are broken with the new update. Using an older version from the website doesn't work either.

**Comment by axeok** [comment] 2024-10-11 01:05
For the temp fix I roll back to old version of Rider, save theme config, update Rider again and import saved theme

**Comment by bukk530** [comment] 2024-10-11 13:41
Thanks that worked! Is there any ETA for a fix? @homatyano @mfilippov, thanks :)

**Comment by homatyano** [comment] 2024-10-11 13:49
The issue is resolved and the fix is published here. It will be included in the next Rider builds, namely 2024.2.7 and 2024.3 EAP 4. As far as I know, they will be released in a week or two.

**Comment by bukk530** [comment] 2024-10-11 13:55
Thank you very much

**Closed** 2024-10-11 14:09 UTC
